--1번 문제

SELECT
    EMPNO,
    ENAME,
    HIREDATE,
    TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), 'monday'), 'yyyy-mm-dd')AS R_JOB, 
    --DECODE(COMM, NULL, 'N/A', COMM ) AS COMM 
    nvl(TO_CHAR(COMM /*NCHAR NCHAR*/),'N/A')
FROM EMP;

--2번 문제
SELECT
    EMPNO,
    ENAME,
    SAL,
    TRUNC( SAL/21.5,2) AS DAY_PAY,
    ROUND((SAL/21.5)/8,1) AS TIME_PAY
FROM
    EMP;

--3번 문제
SELECT
    EMPNO,
    REPLACE(EMPNO, SUBSTR(EMPNO, 3, 2), '**')     AS MASKING_EMPNO,
    ENAME,
    REPLACE(ENAME, SUBSTR(ENAME, 3, 10 ), '****') AS MASKING_ENAME
FROM
    EMP
WHERE
    LENGTH(ENAME) IN 5;

--
SELECT SUM(COMM), SUM(SAL), SUM(DISTINCT SAL), SUM(ALL SAL) FROM EMP;
SELECT MAX(SAL), MIN(SAL) FROM EMP;
SELECT COUNT(*), COUNT(SAL), COUNT(DISTINCT SAL), COUNT(ALL SAL) FROM EMP;

SELECT * FROM EMP;
INSERT INTO EMP VALUES (7566, 'JONES', 'MANAGER', 7839, TO_DATE('1981-04-02', 'YYYY-MM-DD'), 2975, NULL, 20);
INSERT INTO EMP VALUES (7499, 'ALLEN', 'SALESMAN', 7698, TO_DATE('1981-02-20', 'YYYY-MM-DD'), 1600, 300, 30);
INSERT INTO EMP VALUES (7521, 'WARD', 'SALESMAN', 7698, TO_DATE('1981-02-22', 'YYYY-MM-DD'), 1250, 500, 30);

select COUNT(* ) from emp;
SELECT ROUND(AVG(SAL) ,2) as sal_average FROM EMP WHERE DEPTNO = 30;
SELECT AVG(SAL), DEPTNO  FROM EMP GROUP by DEPTNO;

SELECT DEPTNO, JOB, AVG(SAL)
FROM EMP
CUBEBY DEPTNO, JOB
HAVING AVG(SAL) >= 2000
ORDER BY DEPTNO, JOB;

select deptno, job, count(*), MAX(sal), sum(sal), ROUND(avg(sal),2)
from EMP
GROUP BY ROLLUP(deptno, job);

SELECT DEPTNO, JOB, COUNT(*)
FROM EMP
GROUP BY GROUPING SETS(DEPTNO, JOB);

SELECT DEPTNO, LISTAGG(ENAME, ',') WITHIN GROUP(ORDER BY SAL DESC) AS ENAMES
FROM EMP
GROUP BY DEPTNO;

SELECT *
FROM (SELECT DEPTNO, JOB, SAL FROM EMP)
PIVOT(MAX(SAL) FOR DEPTNO IN (10, 20, 30))
ORDER BY JOB;

--실습 문제

--1번문제

SELECT 
deptno, 
ROUND(AVG(SAL),0) AS AVG_SAL, 
MAX(SAL) as MAX_SAL,
MIN(SAL) as MIN_SAL,
COUNT(*)  AS CNT
FROM EMP
GROUP by deptno;

--2번 문제

SELECT
JOB,COUNT(*)
FROM EMP
GROUP BY job
having COUNT(* ) >= 3;

--3번 문제
select
    TO_CHAR(HIREDATE,'YYYY') AS HIRE_YEAR,
    DEPTNO,
    COUNT(* ) AS CNT
from EMP
group BY TO_CHAR(HIREDATE,'YYYY') ,DEPTNO
ORDER  BY TO_CHAR(HIREDATE,'YYYY') DESC;
