--1번 문제
SELECT
    DISTINCT JOB
FROM
    EMP;

-- 2-1번문제
SELECT
    *
FROM
    EMP;

SELECT
    *
FROM
    EMP
ORDER BY
    ENAME DESC,
    JOB;

--2-2번 문제
SELECT
    EMPNO  AS EMPLOYEE,
    ENAME  AS EMPLOYEE,
    MGR    AS MANAGER,
    SAL    AS SALARY,
    COMM   AS COMMISSION,
    DEPTNO AS DEPARTMENT_NO
FROM
    EMP;

SELECT
    *
FROM
    EMP
WHERE
    ENAME = 'KING';

SELECT
    EMPNO,
    ENAME,
    SAL
FROM
    EMP
WHERE
    SAL <= 1500
ORDER BY
    SAL DESC;

SELECT
    ENAME,
    JOB,
    SAL
FROM
    EMP
WHERE
    JOB = 'MANAGER'
    OR JOB = 'SALESMAN'
    AND SAL >1000;

SELECT
    ENAME,
    JOB,
    SAL
FROM
    EMP
WHERE
    (JOB = 'MANAGER'
    OR JOB = 'SALESMAN' )
    AND SAL >1000;

SELECT
    *
FROM
    EMP
WHERE
    JOB NOT IN ('MANAGER', 'CLERK')
ORDER BY
    SAL DESC;

SELECT
    *
FROM
    EMP
WHERE
    SAL BETWEEN 2000 AND 3000;

SELECT
    *
FROM
    EMP
WHERE
    ENAME LIKE '__A%';

SELECT
    *
FROM
    EMP
WHERE
    ENAME LIKE '%AM%';

SELECT
    *
FROM
    EMP
WHERE
    COMM IS NOT NULL;

--실습문제
--1번 문제
SELECT
    *
FROM
    EMP
WHERE
    ENAME LIKE '%S';

--2번 문제
SELECT
    ENAME,
    EMPNO,
    SAL,
    DEPTNO
FROM
    EMP
WHERE
    ENAME LIKE '%E%'
    AND DEPTNO = 30
    AND SAL BETWEEN 1000 AND 2000;

--3번 문제
SELECT
    EMPNO,
    ENAME,
    JOB,
    SAL,
    DEPTNO
FROM
    EMP
WHERE
    DEPTNO = 30
    AND JOB = 'SALESMAN';

SELECT
    DEPTNO
FROM
    EMP
UNION
SELECT
    DEPTNO
FROM
    DEPT;

SELECT  DEPTNO FROM  EMP 
INTERSECT
SELECT  DEPTNO FROM DEPT;

SELECT ENAME, INITCAP(ENAME), UPPER(ENAME), LOWER(ENAME) FROM EMP;

SELECT ENAME, LENGTH(ENAME) FROM EMP WHERE LENGTH(ENAME) >= 5;

SELECT CONCAT(EMPNO, ENAME), CONCAT(EMPNO, CONCAT(' : ', ENAME)) FROM EMP WHERE ENAME = 'SCOTT';

SELECT JOB, SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5)
FROM EMP;

SELECT REPLACE('010-1234-5678', '-', '') AS REPLACE FROM DUAL;

SELECT JOB, SUBSTR(JOB, 3, 2), SUBSTR(JOB, 5) FROM EMP;

SELECT INSTR('HELLO, ORACLE!', 'L') AS INSTR1, INSTR('HELLO, ORACLE!', 'L', 5) AS INSTR2 FROM DUAL;

SELECT TRIM(' _ORACLE_ ') AS TRIM, LTRIM(' +ORACLE+ ') AS LTRIM, RTRIM(' -ORACLE- ') AS RTRIM FROM DUAL;

SELECT ROUND(1234.5678, 2) AS ROUND1 FROM DUAL;

SELECT TRUNC(1234.5678, 2) AS ROUND1 FROM DUAL;

SELECT CEIL(3.14) AS CEIL, FLOOR(3.14) AS FLOOR FROM DUAL;

SELECT MOD(15, 6) AS MOD1, MOD(10, 2) MOD2 FROM DUAL;

SELECT SYSDATE AS NOW, SYSDATE-1 AS YESTERDAY, SYSDATE+1 AS TOMORROW FROM DUAL;

SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3) FROM DUAL;

SELECT EMPNO, ENAME, HIREDATE, SYSDATE, MONTHS_BETWEEN(HIREDATE, SYSDATE) AS MONTH1, MONTHS_BETWEEN(SYSDATE, HIREDATE) AS MONTH2 FROM EMP;

SELECT SYSDATE, NEXT_DAY(SYSDATE ,'monday'), LAST_DAY(SYSDATE) FROM DUAL;